const FILTER_ERROR = 'SORRY, NO RECORD FOUND. PLEASE TRY AGAIN'
const API_ERROR = 'API CONNECTION ERROR. PLEASE CONTACT THE IT DEPARTMENT'

export default {
  FILTER_ERROR: FILTER_ERROR,
  API_ERROR: API_ERROR
}